### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by PyryV** [Dforssi/AlphaKPS#1]
# Vertaisarviointi 
Projekti ladattu 14.2. klo 13.52

Yleisesti sovellus näytti todella hyvältä ja esimerkiksi JavaDocien määrä kaikissa luokissa oli aivan valtava, mikä helpotti ohjelman toiminnan ymmärtämistä huomattavasti. Muutenkin ylesiesti ottaen koodi oli selkeää ja metodien, luokkien sekä muuttujien nimet olivat hyvin niiden tehtäviä kuvaavia. Ohjelman rakenne on myös selkeästi jaoteltu ja näyttäisi noudattavan hyvin single responsibility -periaatetta. 

## Käyttöliittymä
Käyttöliittymä on hyvin selkeä ja helppokäyttöinen. Toivoisin ehkä, että käyttölittymä näyttäisi jokaisen kierroksen jälkeen pistetilanteen esimerkiksi tyyliin voitot-tasapelit-häviöt, jotta pysyisi paremmin kärryillä missä mennään. Ainoa bugi mitä löysin oli se, että kun ohjelman lopettaa täyttyy konsoli virheilmoituksista, mitkä johtuivat näköjään siitä, että Alphakps-luokan lopussa System.exit() saa muuttujan arvoksi 404 eikä 0. 

## AI
Tekoäly on välillä ärsyttävänkin hyvä ja tuntuu etten millään saa voitettua yli 50 prosenttia kierroksista. Olikin mielenkiintoista kokeilla eri strategioita tekoälyä vastaan, josta lopulta mikään ei tuntunut toimivan. Joten tekoälyn tasosta ei mitään valitettavaa. Hyvänä lisänä on myös mahdollisuus vertailla miten erityyppiset tekoälyt pärjäävät toisiaan vastaan.

Kaiken kaikkiaan ohjelma oli helposti käytettävä, koodi helposti ymmärrettävää ja tekoäly toimiva.

**Comment by Dforssi** [comment]
Kiitos palautteestasi! On hieman hankalaa suunnitella hyvää käyttöliittymää kun tietää mitä koodi tekee alla, joten kaikki palaute siihen liittyen on arvokasta. Oma IDE:ni ei tulosta virheilmoituksia exitistä, mutta jos näin on muilla käyttäjillä niin asia on ehdottomasti korjattava. Otan palautteesi huomioon ja kehitän niiden pohjalta projektiani eteenpäin!
